# NOTE(jeff): We do not need any particular language here, as we are just
# testing a shell environment!
language: generic

os:
  - osx
  - linux

# compiler:
  # - gcc
  # - clang

# NOTE(jeff): Linux builds require sudo authentication for apt-get install
sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get update; fi

  - echo -e "NOM_PLATFORM=localhost\nNOM_HOSTNAME=localhost" > $HOME/.bash_env

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install coreutils grc; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get install grc; fi
script:
  # TODO(jeff): Perhaps the use of something like Expect could help us verify
  # that our aliases are setup correctly..?
  - /bin/bash ${HOME}/bin/install.sh
  - /bin/bash ${HOME}/bin/setup_darwin.sh
  - echo $NOM_PLATFORM
  - echo $NOM_HOSTNAME
  - env
  - /bin/bash ${HOME}/bin/remove.sh

# whitelist
# branches:
  # only:
    # - feature/travis
    # - master

notifications:
  email: false
